include_some
qulacs/qulacs pull request #330
Opened 2022-09-13 08:38 UTC by WATLE

まとめてインクルードするファイルを定義した

2022-09-13 21:46 UTC, forest1040 approved these changes
Good!

2022-09-14 03:14 UTC, kotamanegi reviewed
ユーザが利用するファイルとして一括includeがあると良いとは思いますが、testコード内で(includeが可能かを検証する用途以外で)使うのは強く反対します。
理由は3つあります。
- 使われていないにも関わらず依存が発生する
  テストコードを書くときには、どのファイルに書かれている関数かを意識して書くことになるはずです。必要なはずなのに使われていないincludeがあるということは、実装漏れを示唆します。テスト時にinclude_someを使うことは、そのようなバグの温床を発見できないことに繋がります。

- 暗黙の依存が発生する
  ソースコードA,B とテストコードCについて、A -> Bの依存関係があり、プロトタイプ宣言だけしてあってincludeが書かれていない場合を考えます。 C -> Aと呼び出すとBの実装がないのでエラーとなりますが、include_someを使ってしまうとBは別にincludeされてしまうのでBの実装が存在し、正常にコンパイルできてしまいます。

- 余計なコンパイルとリンク時間が増える
  使っていない部分もコンパイルとリンク作業をする必要があります。

なにか意見があればよろしくお願いします:bow:

2022-09-14 03:15 UTC, kotamanegi requested changes
.

2022-09-14 08:24 UTC, forest1040 commented
> 暗黙の依存が発生する

A -> Bの依存関係があるので、AにBのヘッダをincludeしておく形になるかと思います。
ですので、テストコードのCでinclude_someをincludeしようがしまいがあまり関係ないような気もします。。
関係ない依存が増えるのはその通りだとは思います。（がまぁいいかなという気もします。）

> 余計なコンパイルとリンク時間が増える

テストプログラムは結局1バイナリになるので、そんなにコンパイルとリンク時間は変わらない気がします。。

> 使われていないにも関わらず依存が発生する

使われていない依存ができるのはその通りだと思います。（がまぁいいかなという気もします。）
`必要なはずなのに使われていないincludeがあるということは、実装漏れを示唆します。`というのがよくわかりませんでした。。
テストコードで厳密な依存関係だけをテストしたいというのであればわかります。

2022-09-21 00:58 UTC, forest1040 commented
include_someの扱いどうしますか？
ユーザ用だけのincludeファイルにするのであれば、置き場所も変えてしまった方が事故が減るような気がします。
あるいは、廃止しますか。。

2022-09-27 04:56 UTC, ikanago commented
> 暗黙の依存が発生する

これは一括 include をしていると検知が難しいところで，一番問題になりそうです．

> 余計なコンパイルとリンク時間が増える

確かにテストコードは1つのバイナリにリンクされるのであまり問題にはならなさそうです(測定しないと分かりませんが)．

2022-10-04 07:52 UTC, kotamanegi commented
一番恐れているのは，将来cppsimから一部のファイルを消去する場合に，どのファイルが依存しているかわからなくなるという問題です．
includeで明示しているならば，ファイルの先頭を見れば依存関係はわかります．
ところが，全部を一括includeしてしまうと，ファイルの一部を変更すると他の部分でコンパイルエラーが出るジェンガと化します．

2022-10-04 09:22 UTC, forest1040 commented
> 一番恐れているのは，将来cppsimから一部のファイルを消去する場合に，どのファイルが依存しているかわからなくなるという問題です．

なるほど。たしかにそうですね！

2022-11-22 06:36 UTC, closed without merging