Reak naosu
qulacs/qulacs pull request #331
Opened 2022-09-15 08:18 UTC by WATLE

・add_operator_copyとadd_operator_move? を作る
・RotX,RotInvX　を定義する
・qulacs内で書かれているものを新しいほうに置換する

2022-09-20 05:10 UTC, kotamanegi requested changes
プルリクありがとうございます！
かなり多めのコメントになってしまいましたが、目を通していただけると嬉しいです:bow:

2022-09-20 05:10 UTC, kotamanegi commented on src/cppsim/general_quantum_operator.hpp
> +     * copyを内部で行わないので、mptのメモリの開放はGeneralQuantumOperatorがやる
```suggestion
     * 引数で与えられたPauliOperatorの所有権はGeneralQuantumOperator側に譲渡(move)される。
     * したがって、mptのメモリの解放はGeneralQuantumOperator側が行う。
```

2022-09-20 05:10 UTC, kotamanegi commented on src/cppsim/general_quantum_operator.hpp
> +     * copyを内部で行うので、mptのメモリの開放は呼び出し側がやる
```suggestion
     * 引数で与えられたPauliOperatorはGeneralQuantumOperatorに複製(copy)される。
     * したがって、mptのメモリの解放は呼び出し側でも行う必要がある。
```

2022-09-20 07:26 UTC, WATLE commented on test/cppsim/test_circuit.cpp
> +    circuit.add_RX_gate(target, angle * 2);
「// RX +RotInvX - RotX = angle」と書かれている通り、　3つのゲートを通した結果、RX(target,angle)だけ回転します

2022-09-20 07:32 UTC, WATLE commented on test/cppsim/test_gate.cpp
> +    funclist.push_back(std::make_pair(gate::RotInvZ, Z));
たまにはRotInvを使いたくならない?

2022-09-20 07:32 UTC, WATLE commented on src/cppsim/general_quantum_operator.hpp
> +     * copyを内部で行うので、mptのメモリの開放は呼び出し側がやる
ありがとうございます。そうしました

2022-09-20 07:32 UTC, WATLE commented on src/cppsim/general_quantum_operator.hpp
> +     * 従来通り、copyを行う
そうしましたが、「従来通り」の一言だけは残しました

2022-09-21 02:06 UTC, kotamanegi commented on test/cppsim/test_gate.cpp
> +    funclist.push_back(std::make_pair(gate::RotInvZ, Z));
どちらかというと、RotInv用のテストを作るというのが正攻法に思えます。

2022-09-21 02:07 UTC, kotamanegi commented on test/cppsim/test_circuit.cpp
> +    circuit.add_RX_gate(target, angle * 2);
よくわかっていないのですが、修正前のテストコードは間違っていたということですか？

2022-09-21 02:13 UTC, kotamanegi approved these changes
だいたいいい感じになったと思います。
個人的にはLGTMですが、mergeは他の方の意見も聞いてからでお願いします。

2022-09-22 00:29 UTC, forest1040 approved these changes
意図がよくわかるようになって、大変よいと思います！

2022-09-22 06:11 UTC, merged