Kotamanegi/fix cppsim memory leak
qulacs/qulacs pull request #369
Opened 2022-10-20 08:39 UTC by kotamanegi

[Qulacs-Osaka#.355](https://github.com/Qulacs-Osaka/qulacs-osaka/issues/355)

このPRでは、`src/cppsim`と`test/cppsim`内で発生しているAddressSanitizerのエラーを解決します。

`src/cppsim`内の大きな変更として、general_quantum_operatorの四則演算の方法を変更しました。
また、general_quantum_operatorの掛け算について、メモリリークが生じている箇所があったため修正しました。

2022-10-20 09:08 UTC, WATLE approved these changes

2022-10-21 00:01 UTC, forest1040 approved these changes
LGTM!

2022-10-24 09:13 UTC, KowerKoint requested changes
#374 と両方手元で合わせてメモリリークの解消が確認できました。
ありがとうございます。
一箇所スクリプトの訂正だけ提案します。

2022-10-24 09:13 UTC, KowerKoint commented on src/cppsim/gate_noisy_evolution.hpp
> +        delete iH;
upstreamではコンストラクタの実装がgate_noisy_evolution.cppに移ってるので反映を忘れない

2022-10-25 06:05 UTC, ikanago approved these changes
LGTM です!

2022-11-08 08:18 UTC, KowerKoint approved these changes

2022-11-10 06:01 UTC, merged