Inverse
qulacs/qulacs pull request #381
Opened 2022-10-25 08:59 UTC by WATLE

逆ゲートと逆回路を定義しました

2022-10-26 00:45 UTC, forest1040 commented
実装が早い！DenseMatrixの逆回路もあるといいかも知れません。。

2022-10-26 09:01 UTC, KowerKoint requested changes
機能追加ありがとうございます。
2点気になったことがあるので提案させていただきます。

### 返り値を派生クラスのものにする
この関数は`copy()`と同じように自身と同じ種類のゲートを返す設計になっているはずなので具体化の方針に合わせたほうがいいと思っています。

### `QuantumGateBase`に対しては純粋仮想関数として用意する
@forest1040 さんがおっしゃってた「DenseMatrixに対しての実装がない」というのは基底クラスでの実装である`gate::get_adjoint_gate()`を呼び出すことがDenseMatrixに対する逆ゲートの作成として最適であるからだと思うのですが、1量子ゲートなどに対してはオーバーライドしている状態であるようにゲートによって適切な精製方法が異なるのが普通であることから、基底クラスでは純粋仮想関数にしておいて、
- DenseMatrixには`gate::get_adjoint_gate()`
- パウリゲートや1量子ゲートなどにはそれに対応する同種のゲート
- その他定義不能なものは`NotImplementedException`を吐く

という実装にしたほうが事故が少ないかなと思いました。
これも`copy()`と同じ方針です。

2022-10-27 06:36 UTC, WATLE commented
返り値を派生クラスのものにするのは忘れていたのでそうします

ただの仮想関数ではなく純粋仮想関数にすると、QuantumGateBaseが抽象クラスになってしまってインスタンス化できなくなって崩壊します。

2022-10-27 08:27 UTC, forest1040 approved these changes
get_adjoint_gate()見落としてました。LGTMです！

2022-10-28 04:52 UTC, ikanago commented
実装ありがとうございます．おおむね approve なんですが，

> ただの仮想関数ではなく純粋仮想関数にすると、QuantumGateBaseが抽象クラスになってしまってインスタンス化できなくなって崩壊します。

`QuantumGateBase` はすでに純粋仮想関数をもっているので抽象クラスになっていると思いましたが，どうですか?

2022-11-01 06:28 UTC, WATLE commented
QuantumGateBase は純粋仮想関数を持ってないはずです

2022-11-02 09:43 UTC, KowerKoint commented
`update_quantum_state()`は純粋仮想関数です

2022-11-08 07:16 UTC, WATLE commented
なんかよくわかんないけどそれじゃ駄目だったんです

2022-11-08 08:47 UTC, KowerKoint commented
純粋仮想関数を再実装していない子クラスをインスタンス化できなくなるので全部のゲートに定義する必要が出てきます。
純粋でない仮想関数にする実装もありだとは思いますが、その場合は`QuantumGateBase`については`NotImplemented`にして、行列が定義できることがわかってる`QuantumGateMatrix` `QuantumGateSparseMatrix`について改めて`get_adjoint_gate()`を使った定義を書くと良さそうです。
(`QuantumGateDiagonal`は逆行列も対角なので`QuantumGateDiagonal`を返す定義のほうが嬉しそう)

2022-11-10 10:11 UTC, WATLE commented
_merge

2022-11-10 10:12 UTC, WATLE commented
invalid covariant return type

2022-11-15 02:13 UTC, KowerKoint commented
ありがとうございます
あと`QuantumGateDiagonalMatrix`だけ別で実装したくないですか。

2022-11-15 06:16 UTC, WATLE commented
QuantumGateDiagonalMatrixだけ別で実装したらinvalid covariant return typeってエラー出ました

2022-11-15 08:42 UTC, WATLE commented
もう一度やったらエラー出ませんでした

2022-11-16 08:07 UTC, KowerKoint approved these changes
LGTM

2022-11-17 06:17 UTC, kotamanegi approved these changes
LGTM:+1:

2022-11-17 06:19 UTC, kotamanegi commented
close #373

2022-11-17 07:55 UTC, merged