copy pauli in constructor
qulacs/qulacs pull request #436
Opened 2022-12-07 10:31 UTC by KowerKoint

close #435

2022-12-08 06:07 UTC, forest1040 approved these changes
👍

2022-12-08 06:46 UTC, kotamanegi requested changes
この実装だと、PauliOperatorのコピーができずにメモリリークが発生します。
ClsParametricPauliRotationGate::copyなどが問題の例です。
```
    virtual ClsParametricPauliRotationGate* copy() const override {
        return new ClsParametricPauliRotationGate(_angle,  _pauli->copy());
         // _pauli -> copy()が解放されない
  };
```
このあたりをもうちょっと詰めていただけると助かります。

2022-12-12 08:06 UTC, KowerKoint commented
copy()を行う場合はcopy()を呼び出したもとにメモリ開放の責務が生じるので、`new ClsParametricPauliRotationGate(_angle,  _pauli->copy());` という書き方の方に問題がありますね。
`ClsParametricPauliRotationGate::copy()`の実装の方をpauliそのままわたす流れに変更します。

2022-12-12 08:35 UTC, KowerKoint commented
ClsParametricPauliRotationの構築で渡したpauliが開放されてないものを修正しました。
ついでにbackpropにメモリリークがあったので直しました。

2022-12-15 08:09 UTC, Hiroya-W approved these changes
ありがとうございます！
CIのテストコードの分は、リークしている箇所は無さそうですね。LGTMです！

2023-01-05 06:07 UTC, kotamanegi approved these changes
:+1:

2023-01-05 06:07 UTC, kotamanegi commented
いろいろ訂正していただき、ありがとうございます:bow:

2023-01-10 00:09 UTC, merged