Support for Specifying the Number of Threads using Environment Variables
qulacs/qulacs pull request #462
Opened 2023-01-07 10:05 UTC by m-ymzk

#413 Allows control of thread parallelism in Qulacs to be specified independently のPRとなります

- すべての、```#pragma omp parallel```に対応しました
- OMP_NUM_THREADS=1や、QULACS_NUM_THREADS=1でのgtestのパスを確認済み
- README/Documentの部分の変更案を入れてあります
```
-The number of threads used in Qulacs installed with default options can be controlled via the environment variable `OMP_NUM_THREADS`.
-However, typically this option also affects the parallelization of other libraries.
-If you want to force only Qulacs to use a single thread, You can install single-thread Qulacs with the above command.

+The number of threads used in Qulacs installed with default options can be controlled via the environment variable `OMP_NUM_THREADS` or `QULACS_NUM_THREADS`.
+While `OMP_NUM_THREADS` affects the parallelization of other libraries, `QULACS_NUM_THREADS` controls only the parallelization of QULACS.
+Or, if you want to force only Qulacs to use a single thread, You can install single-thread Qulacs with the above command.
```

2023-01-12 07:48 UTC, kotamanegi reviewed
LGTMです:+1:
ソースコードの可読性が大きく上がりました。ありがとうございます:bow:
ソースコード中のset_qulacs_num_threads()とreset_qulacs_num_threads()の出現回数が同じであることも確認しました。
OMPutilの中身についてはtestがないのですが、set_qulacs_num_threads()の呼び出しによって並列数が変わっていることを確認するテストコード追加をお願いしても良いでしょうか？

2023-01-12 07:49 UTC, kotamanegi approved these changes

2023-01-13 01:06 UTC, kotamanegi approved these changes

2023-01-13 01:06 UTC, kotamanegi commented on test/csim/test_omputil.cpp
> +#ifdef _OPENMP
ありがとうございます:pray:

2023-01-24 07:36 UTC, ikanago commented on src/csim/utility.hpp
> +} OMPutil_;
csim はもはや C のライブラリではないので，C++ の class(あるいは struct)として実装したほうがいいと思います．

2023-01-24 07:37 UTC, ikanago commented on src/csim/utility.hpp
> +typedef OMPutil_* OMPutil;
ポインタであることを隠す意味は薄いと思うので，`class OMPUtil` を定義して `OMPUtil*` を扱うようにしたほうがいいと思います．

2023-01-24 07:39 UTC, ikanago commented on src/csim/utility.cpp
> +    REGISTER_METHOD_POINTER(set_qulacs_num_threads)
class として実装すればこういった操作は必要なくなります．

2023-01-24 07:41 UTC, ikanago commented on src/csim/utility.cpp
> +static UINT qulacs_force_threshold = 0;
このあたりの値は `class OMPUtil` のメンバにしたほうがわかりやすいと思います．

2023-01-24 07:42 UTC, ikanago requested changes
実装ありがとうございます!
レビューが遅くなって申し訳ありません．
`OMPUtil` まわりの実装について提案させていただきました． 🙏

2023-01-24 07:50 UTC, ikanago commented on src/csim/utility.cpp
> +    if (qulacs_force_threshold) threshold = qulacs_force_threshold;
明示的に0との比較をしたほうがわかりやすいと思います．

2023-01-24 07:51 UTC, ikanago requested changes

2023-01-24 07:51 UTC, ikanago commented on src/csim/utility.cpp
> +        if (0 < tmp_val && tmp_val < 1025) qulacs_num_thread_max = tmp_val;
1025や65などのマジックナンバーは定数として定義し，意味を表した名前をつけたほうが意図が明確になると思います．

2023-01-24 08:55 UTC, m-ymzk commented on src/csim/utility.hpp
> +} OMPutil_;
そうですね。Cのままだとかっこ悪いかもと思ったりはしてました。時間見つけて試してみます。

2023-01-24 08:59 UTC, m-ymzk commented on src/csim/utility.hpp
> +typedef OMPutil_* OMPutil;
そうですね。
```typedef OMPutil_* OMPutil;``` は、ビルド時のワーニング対策としての苦肉の策だった気がします。

2023-01-24 08:59 UTC, m-ymzk commented on src/csim/utility.cpp
> +    if (qulacs_force_threshold) threshold = qulacs_force_threshold;
qulacs_force_thresholdは、コンストラクタで設定しなおす変数になります。

2023-01-24 09:00 UTC, m-ymzk commented on src/csim/utility.cpp
> +        if (0 < tmp_val && tmp_val < 1025) qulacs_num_thread_max = tmp_val;
その通りですね

2023-01-25 00:02 UTC, m-ymzk commented on src/csim/utility.cpp
> +        if (0 < tmp_val && tmp_val < 1025) qulacs_num_thread_max = tmp_val;
修正しましたので、確認をお願いします。

2023-01-25 00:03 UTC, m-ymzk commented on src/csim/utility.hpp
> +} OMPutil_;
修正しましたので、確認をお願いします。

2023-01-26 06:48 UTC, kotamanegi approved these changes
横槍を入れますが、LGTMです :+1:
classを毎回作ることによる速度低下を懸念したのですが杞憂でした。
`cmake --build build --target bench` でベンチマークを取ったところ、従来の手法と比較しても誤差の範疇でした。

2023-01-26 07:48 UTC, m-ymzk commented
@kotamanegi ベンチ確認、ありがとうございます。スレッド生成のコストはそこそこ大きいのであまり気にしていなかったのですが、結果的にスレッド使わない小規模のときは要確認でしたね。
一応、初回の呼び出し時に作るインスタンスを使いまわすことで、毎回classを作る事は無いようにはなっています。

2023-01-27 04:08 UTC, ikanago commented on src/csim/utility.hpp
> +    OMPutil& operator=(OMPutil&&) = delete;
👍 🙇

2023-01-27 04:16 UTC, ikanago commented on src/csim/utility.hpp
> +        char* endp;
これらの変数は使われていないので，消してしまったほうがわかりやすいと思います．

2023-01-27 04:17 UTC, ikanago commented on src/csim/utility.hpp
> +            const UINT tmp_val = strtol(tmp, &endp, 0);
`endp` が消えるので，`strtol(tmp, nullptr, 0)` になります．

2023-01-27 04:17 UTC, ikanago commented on src/csim/utility.hpp
> +            const UINT tmp_val = strtol(tmp, &endp, 0);
130行目と同様です．

2023-01-27 04:22 UTC, ikanago commented on src/csim/utility.hpp
> +        if (const char* tmp = std::getenv("QULACS_FORCE_THRESHOLD")) {
この閾値は量子ビット数に関するものなので，名前に nqubit を含めたほうがわかりやすくなると思いました．
特に，ここでは似た名前として thread がすぐ近くで使われているので，混同しやすいかなと思います(僕は一瞬 threshold ってなんだろうとなりました)．
たとえば `QULACS_PARALLEL_NQUBIT_THRESHOLD` のような感じです．

2023-01-27 04:23 UTC, ikanago approved these changes
@m-ymzk 実装ありがとうございます! いくつかコメントしたので確認お願いいたします．
@kotamanegi ベンチマークありがとうございます 🙏

2023-01-27 04:25 UTC, ikanago commented on src/csim/utility.hpp
> +        if (const char* tmp = std::getenv("QULACS_FORCE_THRESHOLD")) {
このクラスにおいては qulacs のスレッド数を操作していることは明らかなので，`QULACS_` という prefix は不要かもしれないです．

2023-01-30 11:02 UTC, merged