Json dev gate named test
qulacs/qulacs pull request #463
Opened 2023-01-10 01:47 UTC by forest1040

2023-01-10 02:48 UTC, KowerKoint commented on src/cppsim/gate_factory.cpp
> +        return sqrtXdag(target_qubit);
ありがとうございます

2023-01-10 02:49 UTC, KowerKoint commented
ここでは各gateの情報がもれなくJSONに収まっているかを見たいので、各ゲートのパラメータはもう少し複雑なもの(乱数とか)を使ったほうが良さそうです。

2023-01-10 05:10 UTC, forest1040 commented
パラメータを乱数にします。

2023-01-10 07:21 UTC, forest1040 commented
DenseMatrixとSparseMatrixは、https://github.com/qulacs/qulacs/pull/467 で別テストを追加しました。

2023-01-11 08:31 UTC, KowerKoint requested changes
すみません。昨日同時に言えばよかったのですが、いくつか見てほしいところがあります。よろしくおねがいします。

2023-01-11 08:31 UTC, KowerKoint commented on python/test/test_qulacs.py
> +            qc = None
Noneに戻している意図ってありますか？(勝手にGCが走ると思ってる)

2023-01-11 08:31 UTC, KowerKoint commented on python/test/test_qulacs.py
> +            qc.update_quantum_state(qs)
QuantumCircuitのJSON変換は別でテストするのでここではCircuitを使わずにゲートごとにテストしたほうが良さそうだと思っています。(何のテストで落ちてるのかを明確にしたいので、CircuitのJSONが間違ってるのにゲートテストで落ちる自体は避けたい)
update_quantum_state()でテストするのは効果的ではありますが、基底状態に対しては計算結果が偏っている傾向があるので`qs.set_Haar_random_state()`などでランダム状態にしてから加えるほうが効果的そうです。また、Probabilisticゲート(ノイズ含む)はそのまま`update_quanutm_state()`を行っても確率的に結果が変動してしまうので、`get_distribution()`で得られる確率分布と`get_gate_list()`で得られるゲートのそれぞれの等価性を検証するのがいいと思います。

2023-01-11 08:31 UTC, KowerKoint commented on python/test/test_qulacs.py
> +                P0(0), P1(0), U1(0, 0.), U2(0, 0., 0.), U3(
U1,U2,U3,RX,RY,RZゲートですが、回転角が0だと意味がないので変えたほうがいいです。

2023-01-11 08:48 UTC, forest1040 commented on python/test/test_qulacs.py
> +            qc = None
参照が残っているとGCが走らないので、参照を明示的に切っています。

2023-01-11 08:49 UTC, forest1040 commented on python/test/test_qulacs.py
> +                P0(0), P1(0), U1(0, 0.), U2(0, 0., 0.), U3(
ありがとうございます。random振っときます。

2023-01-11 08:53 UTC, forest1040 commented on python/test/test_qulacs.py
> +            qc.update_quantum_state(qs)
- ゲート毎にstateチェックするようにします。
- `qs.set_Haar_random_state()`入れます。
- Probabilisticは、他チケットで修正します。（https://github.com/qulacs/qulacs/pull/469）

2023-01-11 09:16 UTC, KowerKoint commented on python/test/test_qulacs.py
> +            qc = None
関数を抜けたら勝手にローカル変数は死ぬので参照が切れませんか

2023-01-12 02:38 UTC, forest1040 commented on python/test/test_qulacs.py
> +            qc = None
そのはずなんですけどね。他のテストコードに併せておきました。

2023-01-12 08:44 UTC, kotamanegi reviewed
:+1:

2023-01-16 08:03 UTC, KowerKoint approved these changes
LGTM

2023-01-18 01:11 UTC, merged