Update 4.1_python_tutorial.md
qulacs/qulacs pull request #483
Opened 2023-01-24 05:25 UTC by tako0218

Add TOFFOLI gate and FREJDKIN gate.
Fix a typo.

2023-01-24 06:12 UTC, ikanago commented
Thank you for adding a tutorial!
Can you add an English version tutorial that corresponds to the section you added in this PR?

2023-01-24 07:06 UTC, Hiroya-W reviewed
Thank you for adding a tutorial!
The added tutorial may be Advanced. This section contains the following text.
> その他のゲートについては、Advancedの章を参照してください。

Why don't you add it after the section `量子ゲート> 特殊ゲート > 多ビットパウリ操作`in the Advanced tutorial?
https://docs.qulacs.org/ja/latest/guide/2.0_python_advanced.html#id26

2023-04-03 10:17 UTC, tako0218 reviewed
[add]merge関数についての説明の追加
[fix]誤字脱字の修正

2023-04-04 05:49 UTC, ikanago requested changes
今回書いてもらった部分について，英語版も追加してもらってもいいですか? 🙏   OSS のドキュメントなので DeepL につっこんでもらっても問題ないと思います．
僕が見落としてるだけで，もし英語版がすでに存在するならマージしてください．

2023-04-04 06:03 UTC, Hiroya-W commented
追加してもらった `merge` 関数に関しては、日本語版、英語版がすでにドキュメントにあるので重複していそうです。どちらも、上級、Advancedのチュートリアルの方に書かれていました。

- ゲートの積：http://docs.qulacs.org/ja/latest/guide/2.0_python_advanced.html#id36
- Gate product：http://docs.qulacs.org/en/latest/guide/2.0_python_advanced.html#Gate-product

TOFFOLIやFREJDKINには英語版ドキュメントは存在しないようで、これはぜひ追加していただけると嬉しいです！

2024-03-14 07:32 UTC, ikanago approved these changes

2024-03-14 07:33 UTC, merged