Release v0.5.5
qulacs/qulacs pull request #491
Opened 2023-01-27 07:01 UTC by ikanago

Release v0.5.5 to support Python 3.11

2023-01-30 06:02 UTC, forest1040 approved these changes
👍

2023-01-30 08:36 UTC, KowerKoint approved these changes
:+1:

2023-01-31 05:34 UTC, Hiroya-W approved these changes
:tada:

2023-02-02 06:02 UTC, kotamanegi approved these changes
:+1:

2023-02-02 06:02 UTC, kotamanegi requested changes
#497 を取り込んでからmergeする。

2023-02-03 01:11 UTC, merged

2023-02-03 01:11 UTC, forest1040 commented
#497 をmainに入れてしまいたいので、マージしました。