fix build warning
qulacs/qulacs pull request #495
Opened 2023-02-01 09:35 UTC by KowerKoint

close #494
コンパイル時のWarningのうち、Qulacsのソースによるものを修正しました。

boostが原因のものはいくつか残っています(特にclangでビルドするとたくさん)。

2023-02-01 09:40 UTC, forest1040 approved these changes
👍 Thank you!

2023-02-02 08:06 UTC, kotamanegi requested changes
警告も減っていい感じです:+1:
strict-aliasingについてはちょっと思うところがあったので、僕の方の解決策とどちらが良いか検討していただきたいです。

2023-02-02 08:06 UTC, kotamanegi commented on src/csim/update_ops_matrix_dense_double.cpp
> +    double* ptr_mat = (double*)ptr_mat_char;
いろいろ検討してみました。
ここを修正するよりは、`mat`の型を`double*`型にして`_element_swap`関数を書き直す方が嬉しいです。

C11 には
> 6.2.5.13 Each complex type has the same representation and alignment requirements as an array type containing exactly two elements of the corresponding real type; the first element is equal to the real part, and the second element to the imaginary part, of the complex number.

とあります。
これを用いることで、`mat`の型を`double*`型と解釈して749行目で`memcpy(mat, _mat, sizeof(CTYPE) * 16);` を実行することが可能です。
`memcpy`関数の内部実装では型を`unsigned char*`型に変換する(=byte-alignedであることを保証する)ので警告も消えます。本質的には二重で作業をやってるだけなので`memcpy`側に集約したほうが安全だと思います。

2023-02-03 05:24 UTC, ikanago approved these changes
修正ありがとうございます!

2023-02-09 09:11 UTC, kotamanegi approved these changes
:+1:

2023-02-15 00:01 UTC, merged