Generate Python API documentation from source code
qulacs/qulacs pull request #518
Opened 2023-02-22 08:01 UTC by Hiroya-W

- #517 

## 概要

現状のPython APIドキュメントでは、`qulacs_core`と表示されてしまう部分が誤解を生みそう、という問題があげられていました。
これを解決するために、stubgenなどで生成したシグネチャ情報である `*.py`, `*.pyi` のソースコードから生成するように考えてみました。

結果的には読み込んだソースコード内の `qulacs_core` の文字列を `qulacs` に置き換えて Sphinx 用のreStructuredtextを生成する方針を採用して、実現することができました。

## 方法

### https://github.com/readthedocs/sphinx-autoapi

ソースコードからドキュメントを生成するためにsphinx-autoapiを使うことにしました。これは `*.py`と`*.pyi`のどちらからも読み込んでくれるようになっています。
どちらからも読み込んだ場合の重複を避けるために、sphnix-autoapiは優先順位を指定でき、それが以下の部分になっています。

https://github.com/qulacs/qulacs/blob/62e562ea05375ddc9db32f308b36e5208d57ffb9/doc/ja/source/conf.py#L80

qulacsで自動生成されるstubファイルは `*.pyi` へ生成されて、Pythonで直接書いた関数などは `*.py` から読み込んでほしいためこのようにしてみています。

### qulacs_coreの置換

単純にソースコードからAPIドキュメントを生成するだけでは、モジュール名がqulacs_coreになってしまうことは変わりありませんでした。そこで、今回は以下の方法で置換することにしました。

https://github.com/qulacs/qulacs/commit/aef9c3fa00d83baa80857d9732bd426027fec148 のコミットで対応しています。sphinx-autoapiは、`*.py`, `*.pyi`から`*.rst`を生成し、sphinxが`*.rst`から`*.html`を生成する流れになっています。
この`*.rst`を生成する際に利用されているテンプレートエンジンJinjaの記法を使って、qulacs_coreの出現部分をqulacsに置き換えることにしています。

また、以下のような書き方で表形式でクラスや関数一覧を表示してくれる機能があります。この一覧にも`qulacs_core`が現れる部分があるのですが、この`autoapisummary`で表示される内容を直接変更することはできなさそうでした。

```
.. autoapisummary::
```

今回は、同等の内容の表を生成するマクロを新たに定義して、関係ある部分を https://github.com/qulacs/qulacs/commit/997669d2f336e0c397533da12dc05aef96aede72 のコミットで置き換えています。

2023-02-24 04:13 UTC, forest1040 approved these changes
👍 Thank you!

2023-02-24 04:18 UTC, ikanago commented on doc/requirements.txt
> +sphinx-autoapi
依存関係はすべてルートの pyproject.toml に書いているのでそっちに移して，このファイルは消してしまってもいいと思うのですがどうでしょうか?  Read the Docs でのビルドに影響しそうですかね?

2023-02-24 04:54 UTC, ikanago commented on doc/en/source/index.md
> +pyRef/index
_build のほうには pyRef/index.html が生成されるため Python のリファレンスがページとしては存在するのですが，doc/en/source/index.md から見て doc/en/source/pyRef/index.md が存在しないため(ビルド時に以下の warning が出ます)，トップページから Python のリファレンスに飛ぶことができなくなっています...
```
/workspaces/qulacs/doc/en/source/index.md:92: WARNING: toctree contains reference to nonexisting document 'pyRef/index'
generating indices... genindex /workspaces/qulacs/doc/en/source/index.md:92: WARNING: toctree contains reference to nonexisting document 'pyRef/index'
```
doc/en/source/pyRef/index.md を作るとこの warning が消えてトップページの TOC にも表示されるようになりました．

ビルドは devcontainer 上で行いました．

2023-02-24 04:56 UTC, ikanago commented on doc/ja/source/index.md
> +pyRef/index
en と同様です．

2023-02-24 04:56 UTC, ikanago requested changes
Python のリファレンスに飛べなくなっていたので修正お願いします 🙏

2023-03-01 00:32 UTC, KowerKoint commented on doc/requirements.txt
> +sphinx-autoapi
逆にpyproject.tomlのほうに書かれていないので`pip install .[doc]`では揃わない状況になっていますね

2023-03-01 01:01 UTC, KowerKoint commented on doc/en/source/index.md
> +pyRef/index
このwarningは出ないし、pyRef/index.rstが生成されて正しく飛べるんですがどういう違いなんでしょう……
devcontainerでdoc/下のignoreファイルを消してから`make html`をやっています。

2023-03-01 05:23 UTC, Hiroya-W commented on doc/requirements.txt
> +sphinx-autoapi
> 依存関係はすべてルートの pyproject.toml に書いているのでそっちに移して，このファイルは消してしまってもいいと思うのですがどうでしょうか? Read the Docs でのビルドに影響しそうですかね?

これ、統合できた方が嬉しいしやりたいことではあるんですが、懸念点の通りRead the Docsでのビルドではrequirements.txtから依存パッケージをインストールすることになっていて、それを調整する必要がありそうです。
https://github.com/readthedocs/readthedocs.org/issues/4912 poetryサポートもあるようですし、pyproject.tomlから読む方法はなにかあるかもしれません。改めて調査してみます。

2023-03-01 05:25 UTC, Hiroya-W commented on doc/requirements.txt
> +sphinx-autoapi
> 逆にpyproject.tomlのほうに書かれていないので`pip install .[doc]`では揃わない状況になっていますね

現状としては、requirements.txt、pyproject.tomlのどちらにも書いておく運用が正しくて、pyproject.tomlに書き忘れていました。追記しておきます（こうゆうことがあるので早めに統合したい）

2023-03-01 05:52 UTC, Hiroya-W commented on doc/en/source/index.md
> +pyRef/index
少し手元でも確認していました。
コミットからは `doc/en/source/pyRef/modules.rst` を削除して、代わりに `doc/en/source/pyRef/index.rst` が置かれるような挙動にしているのは意図的で、合っています。
`doc/en/source/pyRef/index.rst` は無いけど、じゃあどこから生成されるのか？についてですが、`_templates/autoapi/index.rst` が対応していて、ここから自動生成されるようになっています。

2023-03-01 06:07 UTC, Hiroya-W commented on doc/en/source/index.md
> +pyRef/index
rstファイルの出力先は、`conf.py` の `autoapi_root = "pyRef"` ですね。
なので生成されていてほしいんですが、やれそうなこととしては、KowerKointさんも試してみてくれているように、事前に生成されていたもの、かつ、Git管理されないものを削除してやりなおしてみるとかでしょうか...。
中間ファイルは確認するためにhtmlを生成した後も、rstファイルが残るように、`conf.py` に `autoapi_keep_files = True`を設定しているので、`pyRef` フォルダが残る仕様になっています。
もし、残っていることが原因な場合はこの設定が今後も影響を与えるかもしれないので、html生成後は `pyRef`フォルダも削除されるようにしてみるべきかな、とも思いました

2023-03-01 08:43 UTC, Hiroya-W commented on doc/en/source/index.md
> +pyRef/index
PRに対して、ドキュメントのpreviewをビルドするようにしてみました。Read the Docs上では上手く動いている様子です...！
https://qulacs-rtd--518.org.readthedocs.build/en/518/

2023-03-02 04:11 UTC, ikanago commented on doc/en/source/index.md
> +pyRef/index
このブランチの最新のコミットに対して，doc/ 以下の Git 管理されていないファイルをすべて削除したら Python リファレンスへのリンクが正しく表示されていました!  お騒がせしました 🙏

2023-03-02 04:12 UTC, ikanago commented on pyproject.toml
> +    "sphinx-autoapi"
🙏

2023-03-02 04:12 UTC, ikanago approved these changes
LGTM です!

2023-03-02 05:57 UTC, Hiroya-W commented on doc/requirements.txt
> +sphinx-autoapi
依存パッケージ関係については解決出来そうで、 #522 でPRにしました

2023-03-03 00:05 UTC, KowerKoint approved these changes
ありがとうございます

2023-03-08 05:15 UTC, merged