remove checkCudaErros() without filename and line
qulacs/qulacs pull request #536
Opened 2023-04-05 03:59 UTC by KowerKoint

close #535
In addition to the description in Issue, erase https://github.com/qulacs/qulacs/blob/3f4ada5a25257ababc8b8edd48bbfb657b924e1b/src/gpusim/memory_ops.cu#L80 line, which is not needed

2023-04-07 04:16 UTC, ikanago requested changes

2023-04-07 04:16 UTC, ikanago commented on src/gpusim/memory_ops.cu
> +    checkCudaErrors(cudaMalloc((void**)&rnd_state, dim * sizeof(curandState),
たぶん `)` がひとつ足りなくてビルドに失敗してるので修正お願いします 🙏 
```suggestion
    checkCudaErrors(cudaMalloc((void**)&rnd_state, dim * sizeof(curandState)),
```

2023-04-11 04:03 UTC, ikanago requested changes

2023-04-11 04:03 UTC, ikanago commented on src/gpusim/memory_ops.cu
> +                        __FILE__, __LINE__),
この行が余分っぽくてコンパイルエラーになっています．僕の修正がおかしかった可能性もあります 🙏

2023-04-14 04:02 UTC, ikanago approved these changes
LGTM です!

2023-04-14 08:06 UTC, forest1040 approved these changes
👍

2023-04-19 00:04 UTC, merged